/*
Copyright (c) 2026 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
*/

syntax = "proto3";

package cleanapi;

import "google/protobuf/descriptor.proto";

message FileOptions {
  // Marks a file as private, so that it will be excluded from the public API.
  bool private = 1;

  // Indicates that the package name should be replaced by this.
  string package = 2;

  // When true, removes google.api.http annotations used for gRPC-to-REST transcoding.
  bool remove_http_options = 3;
}

message MessageOptions {
  // Marks a message as private, so that it will be excluded from the public API.
  bool private = 1;
}

message FieldOptions {
  // Marks a field as private, so that it will be excluded from the public API.
  bool private = 1;
}

message EnumOptions {
  // Marks an enum as private, so that it will be excluded from the public API.
  bool private = 1;
}

message EnumValueOptions {
  // Marks an enum value as private, so that it will be excluded from the public API.
  bool private = 1;
}

message ServiceOptions {
  // Marks a service as private, so that it will be excluded from the public API.
  bool private = 1;
}

message MethodOptions {
  // Mars a field as private, so that it will be excluded from the public API.
  bool private = 1;
}

extend google.protobuf.FileOptions {
  FileOptions file = 50001;
}

extend google.protobuf.MessageOptions {
  MessageOptions message = 50001;
}

extend google.protobuf.FieldOptions {
  FieldOptions field = 50001;
}

extend google.protobuf.EnumOptions {
  EnumOptions enum = 50001;
}

extend google.protobuf.EnumValueOptions {
  EnumValueOptions value = 50001;
}

extend google.protobuf.ServiceOptions {
  ServiceOptions service = 50001;
}

extend google.protobuf.MethodOptions {
  MethodOptions method = 50001;
}
