/*
Copyright (c) 2026 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
*/

syntax = "proto3";

package osac.private.v1;

import "cleanapi/cleanapi.proto";
import "google/api/annotations.proto";

option (cleanapi.file).package = "osac.public.v1";
option (cleanapi.file).http_route_prefix_map = "old:new";

message Image {
  string id = 1;
  string name = 2;
  string internal_status = 3 [(cleanapi.field).private = true];
}

message ImagesGetRequest {
  string id = 1;
}

message ImagesGetResponse {
  Image object = 1;
}

message ImagesCreateRequest {
  Image object = 1;
}

message ImagesCreateResponse {
  Image object = 1;
}

message ImagesStoreRequest {
  option (cleanapi.message).private = true;
  Image object = 1;
}

message ImagesStoreResponse {
  option (cleanapi.message).private = true;
  Image object = 1;
}

service Images {
  rpc Get(ImagesGetRequest) returns (ImagesGetResponse) {
    option (google.api.http) = {
      get: "/api/old/v1/images/{id}"
      response_body: "object"
    };
  }
  rpc Create(ImagesCreateRequest) returns (ImagesCreateResponse) {
    option (google.api.http) = {
      post: "/api/old/v1/images"
      body: "object"
      response_body: "object"
    };
  }

  // Internal method with no HTTP annotation
  rpc Store(ImagesStoreRequest) returns (ImagesStoreResponse) {
    option (cleanapi.method).private = true;
  }
}
